server:
  hostname: "default"
  redis_uri: "redis://localhost:6379"
client:
  aliases:
    - alias: "root-default"
      user: "root"
      hostname: "default"
      redis_uri: "redis://localhost:6379"
